export const POLICIES = [
  {
    id: 1,
    title: "청년전용 보증부월세대출",
    category: "대출지원",
    tag: "자격충족",
    summary: "저소득 청년을 대상으로 보증금과 월세를 동시에 지원하는 전용 대출 상품",
    dDay: "상시접수",
    benefit: "연 1.0%~1.3% 저금리",
    benefitAmount: 1500, // 가치 환산 (단위: 만원)
    probability: 92,
    details: "만 19세~34세, 연소득 5천만원 이하 무주택 청년 대상",
    documents: ["주민등록등본", "가족관계증명서", "소득금액증명원", "임대차계약서"],
    views: 1240,
    applicants: 850,
    minIncome: 0,
    maxIncome: 5000,
    regions: ["전국"],
    occupations: ["대학생", "취업준비생", "직장인", "자영업자"]
  },
  {
    id: 2,
    title: "청년 월세 한시 특별지원",
    category: "월세지원",
    tag: "확인필요",
    summary: "경제적 어려움을 겪는 청년층의 주거비 부담 경감을 위해 월세를 지원",
    dDay: "D-15",
    benefit: "월 최대 20만원 지원",
    benefitAmount: 240,
    probability: 75,
    details: "부모님과 별도 거주하는 무주택 청년 (중위소득 60% 이하)",
    documents: ["월세이체확인증", "임대차계약서", "통장사본"],
    views: 3500,
    applicants: 2100,
    minIncome: 0,
    maxIncome: 2400,
    regions: ["전국"],
    occupations: ["대학생", "취업준비생", "직장인", "자영업자", "기타"]
  },
  {
    id: 3,
    title: "SH/LH 청년 매입임대주택",
    category: "공공임대",
    tag: "자격충족",
    summary: "도심 내 기존 주택을 매입하여 개보수 후 청년들에게 저렴하게 임대",
    dDay: "D-3",
    benefit: "시세의 30~50% 수준",
    benefitAmount: 3000,
    probability: 60,
    details: "대학생, 취업준비생 및 만 19세~39세 청년",
    documents: ["주민등록등본", "자산보유사실확인서", "재학증명서(해당자)"],
    views: 5600,
    applicants: 1200,
    minIncome: 0,
    maxIncome: 4500,
    regions: ["서울", "경기", "인천"],
    occupations: ["대학생", "취업준비생"]
  },
  {
    id: 4,
    title: "청년도약계좌 (주거 특화)",
    category: "자산형성",
    tag: "자격충족",
    summary: "주거 독립 자금 마련을 위한 청년 대상 고금리 저축 상품",
    dDay: "매달 초",
    benefit: "정부 기여금 + 비과세",
    benefitAmount: 500,
    probability: 99,
    details: "개인소득 7,500만원 이하, 가구소득 180% 이하 청년",
    documents: ["소득확인서류", "신분증"],
    views: 8900,
    applicants: 4500,
    minIncome: 0,
    maxIncome: 7500,
    regions: ["전국"],
    occupations: ["직장인", "자영업자"]
  },
  {
    id: 5,
    title: "버팀목 전세자금대출",
    category: "대출지원",
    tag: "자격충족",
    summary: "무주택 서민의 주거 안정을 위한 저금리 전세자금 대출",
    dDay: "상시접수",
    benefit: "연 1.8%~2.7% 금리",
    benefitAmount: 2000,
    probability: 88,
    details: "부부합산 연소득 5천만원 이하 무주택 세대주",
    documents: ["확정일자부 임대차계약서", "주민등록등본", "소득증빙서류"],
    views: 4200,
    applicants: 3100,
    minIncome: 0,
    maxIncome: 5000,
    regions: ["전국"],
    occupations: ["직장인", "자영업자", "기타"]
  },
  {
    id: 6,
    title: "서울시 청년 임차보증금 이자지원",
    category: "대출지원",
    tag: "확인필요",
    summary: "서울 거주 청년들의 주거비 부담 완화를 위한 대출 이자 지원",
    dDay: "상시접수",
    benefit: "연 최대 2.0% 이자지원",
    benefitAmount: 400,
    probability: 85,
    details: "서울 거주 만 19~39세 무주택 청년 소득 4천만원 이하",
    documents: ["주민등록등본", "근로소득원천징수증", "임대차계약서"],
    views: 3100,
    applicants: 1500,
    minIncome: 0,
    maxIncome: 4000,
    regions: ["서울"],
    occupations: ["직장인", "취업준비생"]
  },
  {
    id: 7,
    title: "경기도 청년 기본소득 (주거비 활용)",
    category: "월세지원",
    tag: "자격충족",
    summary: "경기도 거주 청년에게 정기적으로 지급하는 기본 소득",
    dDay: "분기별 접수",
    benefit: "연 100만원 지원",
    benefitAmount: 100,
    probability: 100,
    details: "경기도 내 3년 이상 거주 만 24세 청년",
    documents: ["주민등록초본"],
    views: 6700,
    applicants: 5000,
    minIncome: 0,
    maxIncome: 99999,
    regions: ["경기"],
    occupations: ["대학생", "취업준비생", "직장인", "자영업자", "기타"]
  },
  {
    id: 8,
    title: "행복주택 공급",
    category: "공공임대",
    tag: "확인필요",
    summary: "청년, 신혼부부 등을 위해 직주근접이 가능한 저렴한 공공임대주택",
    dDay: "D-7",
    benefit: "시세 60~80% 수준",
    benefitAmount: 2500,
    probability: 45,
    details: "무주택자로서 도시근로자 가구원수별 월평균소득 100% 이하",
    documents: ["주민등록등본", "청약통장사본", "자산신고서"],
    views: 12000,
    applicants: 8000,
    minIncome: 0,
    maxIncome: 6000,
    regions: ["전국"],
    occupations: ["대학생", "취업준비생", "직장인", "자영업자", "기타"]
  },
  {
    id: 9,
    title: "청년 우대형 청약통장",
    category: "자산형성",
    tag: "자격충족",
    summary: "기존 주택청약종합저축의 기능에 금리 우대 및 비과세 혜택 부여",
    dDay: "상시접수",
    benefit: "최대 4.5% 금리 + 비과세",
    benefitAmount: 300,
    probability: 95,
    details: "만 19~34세, 연소득 3,600만원 이하 무주택 세대주(예정자)",
    documents: ["소득증빙서류", "주민등록등본"],
    views: 9500,
    applicants: 6000,
    minIncome: 0,
    maxIncome: 3600,
    regions: ["전국"],
    occupations: ["대학생", "취업준비생", "직장인", "자영업자", "기타"]
  },
  {
    id: 10,
    title: "디딤돌 대출 (내집마련)",
    category: "대출지원",
    tag: "확인필요",
    summary: "저소득/무주택자에게 저금리로 주택 구입 자금을 대출해주는 제도",
    dDay: "상시접수",
    benefit: "연 2.15%~3.0% 금리",
    benefitAmount: 5000,
    probability: 55,
    details: "부부합산 연소득 6천만원 이하, 순자산 4.69억원 이하",
    documents: ["부동산매매계약서", "주민등록등본", "소득증빙서류"],
    views: 7800,
    applicants: 2000,
    minIncome: 0,
    maxIncome: 6000,
    regions: ["전국"],
    occupations: ["직장인", "자영업자"]
  }
];
